import Link from "next/link";

export default function RestrictedCaseView() {
  return (
    <main
      className="
        relative
        flex
        min-h-screen
        items-center
        overflow-hidden
        bg-[#080b0f]
        py-20
        text-[#eef5f8]
      "
    >
      <div
        aria-hidden="true"
        className="
          pointer-events-none
          absolute
          left-1/2
          top-1/2
          h-[760px]
          w-[760px]
          -translate-x-1/2
          -translate-y-1/2
          rounded-full
          bg-amber-300/[0.05]
          blur-[170px]
        "
      />

      <div
        className="
          container-shell
          relative
          z-10
          w-full
        "
      >
        <div
          className="
            mx-auto
            max-w-[920px]
            rounded-[28px]
            border
            border-amber-300/25
            bg-[#11100d]/95
            p-6
            sm:p-8
            lg:p-12
          "
        >
          <div
            className="
              flex
              flex-wrap
              items-center
              justify-between
              gap-4
            "
          >
            <p
              className="
                font-mono
                text-[10px]
                font-semibold
                tracking-[0.15em]
                text-amber-300
                uppercase
              "
            >
              Restricted Case File
            </p>

            <span
              className="
                rounded-full
                border
                border-amber-300/25
                bg-amber-300/[0.06]
                px-3
                py-2
                font-mono
                text-[9px]
                font-semibold
                tracking-[0.11em]
                text-amber-200
                uppercase
              "
            >
              S-01
            </span>
          </div>

          <h1
            className="
              mt-10
              text-[48px]
              font-semibold
              leading-[0.95]
              tracking-[-0.055em]
              text-amber-100
              uppercase
              sm:text-[68px]
              lg:text-[86px]
            "
          >
            Access
            <br />
            Denied
          </h1>

          <div
            className="
              mt-10
              grid
              gap-3
              border-y
              border-amber-300/[0.15]
              py-6
              sm:grid-cols-3
            "
          >
            <div>
              <p className="tiny-mono">
                Case
              </p>
              <p
                className="
                  mt-2
                  text-[14px]
                  font-semibold
                  text-amber-100
                "
              >
                S-01
              </p>
            </div>

            <div>
              <p className="tiny-mono">
                Disclosure
              </p>
              <p
                className="
                  mt-2
                  text-[14px]
                  font-semibold
                  text-amber-100
                "
              >
                Restricted
              </p>
            </div>

            <div>
              <p className="tiny-mono">
                Clearance
              </p>
              <p
                className="
                  mt-2
                  text-[14px]
                  font-semibold
                  text-amber-100
                "
              >
                Insufficient
              </p>
            </div>
          </div>

          <p
            className="
              mt-8
              max-w-[680px]
              text-[17px]
              leading-8
              text-[#bbb7af]
            "
          >
            Public clearance does not include the technical record for this system. The project remains under active development and no deeper case material is being disclosed.
          </p>

          <Link
            href="/#archive"
            className="
              mt-10
              inline-flex
              min-h-[48px]
              items-center
              justify-center
              rounded-full
              border
              border-amber-300/35
              bg-amber-300/[0.06]
              px-5
              font-mono
              text-[10px]
              font-semibold
              tracking-[0.11em]
              text-amber-100
              uppercase
              outline-none
              transition
              hover:border-amber-300/55
              hover:bg-amber-300/[0.10]
              focus-visible:ring-2
              focus-visible:ring-amber-300/70
              focus-visible:ring-offset-2
              focus-visible:ring-offset-[#080b0f]
            "
          >
            Return to Public Archive
          </Link>
        </div>
      </div>
    </main>
  );
}
